# Generated by Django 3.1.3 on 2020-11-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('selected_type', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
