# Generated by Django 3.1.3 on 2020-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='is_active',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
