# Generated by Django 3.0.7 on 2020-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_register_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('participants', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('sel_type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('accessibility', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
