# Generated by Django 3.0.7 on 2020-11-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_auto_20201110_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='email',
        ),
    ]
