# Generated by Django 3.0.7 on 2020-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0007_auto_20201110_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='user',
        ),
        migrations.AddField(
            model_name='activities',
            name='email',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
