# Generated by Django 3.0.7 on 2020-11-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_auto_20201110_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='email',
            new_name='created_by',
        ),
    ]
