# Generated by Django 3.0.7 on 2020-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0009_auto_20201110_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_user',
            name='mobile',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='selected_type',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
